### ISSUE TITLE
Document how to install requirements for testing

### ISSUE THREAD

**Issue by mjuenema** [mjuenema/otdrparser#13]
There is currently no information on how to install the requirements for running ``make test``:

* **nose** does not work with Python 3.11 and **pynose** must be used.
* The test code cause **nose-parameterized** to raise an exception ``AttributeError: 'tuple' object has no attribute 'args'``
